name: geister
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # hooks
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.6

  # SVG表示用
  flutter_svg: ^2.0.7

  # freezed
  freezed: ^2.3.5
  freezed_annotation: ^2.2.0
  json_serializable: ^6.7.1

  # firebase
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  cloud_functions: ^4.3.3

  # SharedPreferences
  shared_preferences: ^2.2.0

  # 画面遷移
  go_router: ^9.0.0
  go_router_builder: ^2.2.0
  
  # テキストのアニメーション
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # 自動生成
  build_runner: ^2.4.6


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Zen_Maru_Gothic
      fonts: 
         - asset: assets/fonts/ZenMaruGothic/static/ZenMaruGothic-Black.ttf
           weight: 900
         - asset: assets/fonts/ZenMaruGothic/static/ZenMaruGothic-Bold.ttf
           weight: 700
         - asset: assets/fonts/ZenMaruGothic/static/ZenMaruGothic-Medium.ttf
           weight: 500
         - asset: assets/fonts/ZenMaruGothic/static/ZenMaruGothic-Regular.ttf
           weight: 400
         - asset: assets/fonts/ZenMaruGothic/static/ZenMaruGothic-Light.ttf
           weight: 300
    - family: Cherry_Bomb_One
      fonts: 
         - asset: assets/fonts/CherryBombOne/static/CherryBombOne-Regular.ttf
           weight: 400
